const {joinNotes} = require('../lib/helpers')

module.exports = {
  'issue': {
    'title': '🤖🆘 Too many PRs',
    'body': function (prNumbers) {
      return `Dearest humans,

I've run into a problem here. I am trying to update the community docs and to get this repo up-to-scratch. I would usually create a new pull request to let you know about it, or update an existing one. But now there more than one: ${prNumbers.map(number => `#${number}`).join(', ')}

I don’t know how that happened, did I short-circuit again?

You could really help me by closing all pull requests or by leaving open the one you want me to keep updating.

Hope you can fix it (and my circuits) soon. 🙏

Note: This pull request was automatically generated by https://github.com/RichardLitt/build-a-space. Found an issue? [Let me know!](https://github.com/RichardLitt/build-a-space/issues)
`
    }
  },
  'pr': {
    'title': 'Add community documentation',
    'body': function (files) {
      return `Dearest humans,

You are missing some important community files. I am adding them here for you!

Here are some things you should do manually before merging this Pull Request:

${joinNotes(files)}

Note: This pull request was automatically generated by https://github.com/RichardLitt/build-a-space. Found an issue? [Let me know!](https://github.com/RichardLitt/build-a-space/issues)
`
    }
  }
}
